### ISSUE TITLE
update tidy-html5 dependency to release 5.2.0

### ISSUE THREAD

**Issue by rtack** [gagern/node-libtidy#11]
https://github.com/htacg/tidy-html5/releases/tag/5.2.0  is out.
I don't know how this needs to be updated, otherwise I'd provide a pull request.

**Comment by gagern** [comment]
Essentially all one has to do is update the git submodule to the corresponding commit. But I'll take care of it, thanks for informing me of the release.

**Comment by gagern** [comment]
Bumped in 585a52369678bfe9a6c182daa35855828488741f, intend to release that soon.
