### ISSUE TITLE
Help needed: how can I enumerate all options and values

### ISSUE THREAD

**Issue by jokester** [gagern/node-libtidy#14]
I am trying to write a TypeScript type declaration for this library. The declaration would help TypeScript users with better type checking, better code completion and stuff. 

There is already a [working code](https://github.com/jokester/coc-zh/blob/master/tools/lib/libtidy.d.ts) I use in my scripts, but the types for options are far from complete.

I found `TidyDoc#getOptionList()`, but it only includes `output-encoding` and not `output_encoding` `outputEncoding`. Can I have some hint or resources on this?

**Comment by gagern** [comment]
Thank you for writing a TypeScript declaration! Do you want that included with the library?

https://github.com/gagern/node-libtidy/blob/d48be0a7ffc453de0e8d3aa054f93e293eed6148/src/doc.cc#L161-L168 has the conversion rules. Essentially efery dash `foo-bar` can also be written as underscore `foo_bar` or camel case `fooBar`. And you can also mix them, i.e. `foo_barBaz-zap`.

**Comment by jokester** [comment]
Thanks for your reply, that's exactly what I failed to find. 👍 

After finished, I will be more than glad to see the TS declaration be included here.

Can I keep this issue open for a while? I may have more questions about this in next days.

**Comment by jokester** [comment]
Just created a PR with a first version of `.d.ts`. Closing this 🍰
